import "../styles/globals.css"
import type { AppProps } from "next/app"
import Head from "next/head"
import { ApolloProvider } from "@apollo/client"
import client from "../src/configs/apolloClient"
function MyApp({ Component, pageProps }: AppProps) {
	return (
		<ApolloProvider client={client}>
			<Head>
				<title>Me by Myself</title>
				<meta name="description" content="Generated by create next app" />
				<meta property="og:title" content="Me By Myself" />
				<meta property="og:image" content="https://me-by-myself.netlify.app/hearth.png"></meta>
				<link rel="icon" href="/hearth.png" />
			</Head>
			<Component {...pageProps} />
			<div id="portal"></div>
		</ApolloProvider>
	)
}

export default MyApp
