import "../styles/globals.css"
import type { AppProps } from "next/app"
import Head from "next/head"
import { ApolloProvider } from "@apollo/client"
import client from "../src/configs/apolloClient"
function MyApp({ Component, pageProps }: AppProps) {
	return (
		<ApolloProvider client={client}>
			<Head>
				<title>Me by Myself</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</ApolloProvider>
	)
}

export default MyApp
